// Coloque aqui suas actions
const USER_LOGIN = 'USER_LOGIN';
const ADD_EXPENSE = 'ADD_EXPENSE';
const RECEIVE_CURRENCIES = 'RECEIVE_CURRENCIES';
const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
const FAILED_REQUEST = 'FAILED_REQUEST';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const START_EDIT = 'START_EDIT';
const CLOSE_EDIT = 'CLOSE_EDIT';

export {
  USER_LOGIN,
  ADD_EXPENSE,
  RECEIVE_CURRENCIES,
  REQUEST_CURRENCIES,
  FAILED_REQUEST,
  DELETE_EXPENSE,
  START_EDIT,
  CLOSE_EDIT,
};
