// Coloque aqui suas actions
const USER_LOGIN = 'USER_LOGIN';
const ADD_EXPENSE = 'ADD_EXPENSE';
const RECEIVE_CURRENCIES = 'RECEIVE_CURRENCIES';
const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
const FAILED_REQUEST = 'FAILED_REQUEST';

export {
  USER_LOGIN,
  ADD_EXPENSE,
  RECEIVE_CURRENCIES,
  REQUEST_CURRENCIES,
  FAILED_REQUEST,
};
