export const USER = 'USER';
export const SAVE_CURRENCIES = 'SAVE_CURRENCIES';
export const SAVE_EXPENSES = 'SAVE_EXPENSES';
export const EDIT_EXPENSES = 'EDIT_EXPENSES';
export const SAVE_EDITED_EXPENSES = 'SAVE_EDITED_EXPENSES';
export const DELETE_EXPENSES = 'DELETE_EXPENSES';
