const TYPES = {
  ERROR_FETCHING_API: 'ERROR_FETCHING_API',
  FECTHING_API: 'FETCHING_API',
  GET_CURRENCIES: 'GET_CURRENCIES',
  GET_EXCHANGE_RATE: 'GET_EXCHANGE_RATE',
  NEW_EXPENSE: 'NEW_EXPENSE',
  REQ_CURRENCIES: 'REQ_CURRENCIES',
  SAVE_EMAIL: 'SAVE_EMAIL',
};

export default TYPES;
