const types = {
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  REQUEST_COIN: 'REQUEST_COIN',
  FAILED_REQUEST: 'FAILED_REQUEST',
  ADD_EXPENSE: 'ADD_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
};

export default types;
