// USER
export const USER_LOGIN = 'USER_LOGIN';
export const WALLET_ADDCURR = 'WALLET_ADDCURR';
export const WALLET_ADDEXP = 'WALLET_ADDEXP';
export const WALLET_DELEXP = 'WALLET_DELEXP';
export const WALLET_EDITEXP = 'WALLET_EDITEXP';

export const WALLET_ENTER_EDIT_MODE = 'WALLET_ENTER_EDIT_MODE';
export const WALLET_EXIT_EDIT_MODE = 'WALLET_EXIT_EDIT_MODE';
