export const USER_LOGIN = 'USER_LOGIN';
export const REQUEST_CURRENCY = 'REQUEST_CURRENCY';
export const IS_FETCHING = 'IS_FETCHING';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
